[project]

name = "mzpeak"
version = "0.2.0"

dependencies = [
    "pyarrow",
    "pandas",
    "numpy",
    "pynumpress",
    "scipy",
    "psims",
]

license = "Apache-2.0"

[project.optional-dependencies]
sql = ["datafusion"]
cli = ["click"]
